SELECT * FROM customer LIMIT 20; 
-- What is the total revenue GENERATED by male vs female customer?
SELECT gender, sum(purchase_amount) as revenue 
FROM customer 
GROUP by gender;

-- which customers used a discount but still spent more than the average purchase_amount?
SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT avg(purchase_amount) FROM customer);

-- which are the top 5 products with the highest average review_rating?
SELECT item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
GROUP by item_purchased
ORDER by avg(review_rating) DESC LIMIT 5; 

-- Compare the average purchase_amount BETWEEN Standard and Express Shipping.
SELECT shipping_type,
round(avg(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP by shipping_type;

--Do subscribed customer spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers. 
SELECT subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
FROM customer
GROUP by subscription_status 
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchase with discounts applied?
SELECT item_purchased,
round(100 * sum(Case when discount_applied = 'Yes' then 1 else 0 END)/count(*),2) as discount_rate
FROM customer
GROUP by item_purchased
ORDER by discount_rate DESC limit 5;


select * from customer LIMIT 10;

-- Segment customers into New, and Loyal based on their total
-- number of previous_purchases and show the count of each segment.

WITH customer_type as (
SELECT customer_id , previous_purchases,     -- This is a CTE( COMMON TABLE EXPRESSION )
CASE 
	WHEN previous_purchases = 1 THEN "New"
	WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
	ELSE "Loyal"
	END as customer_segment
FROM customer
)

SELECT customer_segment, count(*) as "Number of Customers"
FROM customer_type
GROUP by customer_segment;


-- What are the top 3 most purchased products within each category?
with item_counts as (
SELECT category, 
item_purchased, 
count(customer_id) as total_orders,
row_number() OVER(PARTITION by category ORDER by count(customer_id) DESC) as item_rank
FROM customer 
GROUP by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
from item_counts
WHERE item_rank <= 3;

-- are customerrs who are repeat buyers (more than 5 previous_purchases) also likely to subscribe?
SELECT subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
GROUP by subscription_status

-- what is the revenue contribion of each age group?
SELECT age_group, 
sum (purchase_amount) as total_revenue 
FROM customer 
GROUP by age_group
ORDER by total_revenue desc;